### ISSUE TITLE
the name parameter 'value' is not defined

### ISSUE THREAD

**Issue by klokoleva** [cetorres/multiselect_formfield#13]
already get packages, and try the packages, but always error the parameter value is not defined

![Untitled](https://user-images.githubusercontent.com/11715564/81894497-1f5fc280-95da-11ea-98cc-ce4a72febf5a.png)

**Comment by sathishmscict** [comment]
Same issue in existing project, am not made any changes in my code but am facing same issue : "error: The named parameter 'value' isn't defined. (undefined_named_parameter at [projectName] lib\ui\FiltersScreen.dart:170)"

**Comment by silios** [comment]
Just run an pub upgrade and got the latest version 0.1.3 (was running on 0.1.2) and the IDE complained about non defined 'value'.

It looks like it's been replaced by 'initialValue' -> https://github.com/cetorres/multiselect_formfield/commit/5ad9fdd6195d237bad1e5a589166fd8742fc5435

**Comment by klokoleva** [comment]
thanks, solved
