### ISSUE TITLE
 multiselect_formfield not working with flutter 2.8.0

### ISSUE THREAD

**Issue by syedbilal07** [cetorres/multiselect_formfield#48]
Hi folks,
Please update this package. I am using 0.16 (latest). It was running fine with flutter 2.5.3, now I have upgraded to 2.8.0 and this package is not working with android/ios, It says "Error: No named parameter with the name 'autovalidate'.". Please see the attached screenshot and solve it soon. Thanks.
![Capture](https://user-images.githubusercontent.com/16761960/146030308-4d1132d6-c876-48e8-b64f-f45134f22393.JPG)

**Comment by joseph-fox** [comment]
I am having the same issue.

**Comment by joseph-fox** [comment]
@syedbilal07 a temporary hack:

```
  multiselect_formfield:
    git: https://github.com/FariJan/multiselect_formfield.git
```

@FariJan has a PR https://github.com/cetorres/multiselect_formfield/pull/47 and it address the compatibility issue.

**Comment by cetorres** [comment]
Hi guys. I'm going to fix this issue. I'm finding a time this week to do that. Thanks for bringing that up.

**Comment by syedbilal07** [comment]
Thanks @cetorres

**Comment by SainathChallagundla** [comment]
> Hi folks, Please update this package. I am using 0.16 (latest). It was running fine with flutter 2.5.3, now I have upgraded to 2.8.0 and this package is not working with android/ios, It says "Error: No named parameter with the name 'autovalidate'.". Please see the attached screenshot and solve it soon. Thanks. ![Capture](https://user-images.githubusercontent.com/16761960/146030308-4d1132d6-c876-48e8-b64f-f45134f22393.JPG)

Hi 
do you  have any other solution for that.

**Comment by SainathChallagundla** [comment]
> Hi guys. I'm going to fix this issue. I'm finding a time this week to do that. Thanks for bringing that up.

Thank you for your quick response.
Hope it will fix as soon as possible.

**Comment by cetorres** [comment]
Updated to work with Flutter 2.8.0 with PR #47. Thanks @FariJan!

**Comment by syedbilal07** [comment]
Tested with Flutter 2.8.1 also ?
