### ISSUE TITLE
Set Pre-selected values 

### ISSUE THREAD

**Issue by LenvZyl** [cetorres/multiselect_formfield#5]
How does one have values preselected when the Widget is built.
Setting `value` only returns an Error and `initialValue` only takes an int.

**Comment by cetorres** [comment]
To set pre selected values, pass an array of the same type of the values of the field.

**Comment by abdulwahid24** [comment]
@cetorres Would you please provide an example of how exactly we can have pre-selected data.

**Comment by guit4eva** [comment]
> @cetorres Would you please provide an example of how exactly we can have pre-selected data.

example: initialValue: ["Running"]
